name: Update Top Languages

on:
  schedule:
    - cron: '0 0 * * *'  # tiap hari tengah malam UTC
  workflow_dispatch: {}  # bisa dijalankan manual dari tab Actions

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # penting agar pakai token di bawah

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python tools/update_top_langs.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "chore: update top languages"
            git push
          fi
